version: "3.3"

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ApiServer-app
    ports:
      - 9090:9090
    volumes:
      - ./:/try/backend

  db:
    container_name: ApiServer-db
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "develop"
    volumes:
      - db-store:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-store: